test_configs:
- name: gemini-2.5-pro
  input_path: problem_set/ABench/test.jsonl
  output_path: test_results/ABench/CoT-SC/Gemini-2.5-pro/results.jsonl
  scheme: single-llm
  temperature: 0.5
  models:
    generator: gemini-2.5-pro
  single_llm_options:
    voting_n: 5
  tools: []
global_settings:
  concurrent_limit: 10
  aux_dir_base: .aux
