test_configs:
  - name: "gemini-2.5-pro"
    input_path: "problem_set/ABench/test.jsonl"
    output_path: "src/loca/results/ABench/Gemini-2.5-pro_Review_Solution/improved_solution.jsonl"
    scheme: "loca"
    temperature: 0.0
    models:
      generator: "gemini-2.5-pro"
      reviewer: "gemini-2.5-pro"
    loca_options:
      refine_model: "gemini-2.5-pro"
      max_error_times: 5
      target_times: 3

global_settings:
  concurrent_limit: 10
  aux_dir_base: ".aux"
