test_configs:
- name: gemini-2.5-pro
  input_path: problem_set/PHYSICS/test.jsonl
  output_path: test_results/PHYSICS/CoT/Gemini-2.5-pro/results.jsonl
  scheme: single-llm
  temperature: 0.0
  models:
    generator: gemini-2.5-pro
  single_llm_options:
    cot: true
  tools: []
global_settings:
  concurrent_limit: 10
  aux_dir_base: .aux
