test_configs:
  - name: "gemini-2.5-pro"
    input_path: "problem_set/PHYBENCH_100/test.jsonl"
    output_path: "test_results/PHYBench/MAD/Gemini-2.5-pro/results.jsonl"
    scheme: "mad"
    temperature: 0.0
    models:
      generator: "gemini-2.5-pro"
    mad_options:
      debate_model: "gemini-2.5-pro"
      max_rounds: 3
      config_file: "src/mad/config.json"
    tools: []

  - name: "o3-2025-04-16"
    input_path: "problem_set/PHYBENCH_100/test.jsonl"
    output_path: "test_results/PHYBench/MAD/o3-2025-04-16/results.jsonl"
    scheme: "mad"
    temperature: 0.0
    models:
      generator: "o3-2025-04-16"
    mad_options:
      debate_model: "o3-2025-04-16"
      max_rounds: 3
      config_file: "src/mad/config.json"
    tools: []

  - name: "gpt-5"
    input_path: "problem_set/PHYBENCH_100/test.jsonl"
    output_path: "test_results/PHYBench/MAD/GPT-5/results.jsonl"
    scheme: "mad"
    temperature: 0.0
    models:
      generator: "gpt-5"
    mad_options:
      debate_model: "gpt-5"
      max_rounds: 3
      config_file: "src/mad/config.json"
    tools: []

  - name: "deepseek-r1-250528"
    input_path: "problem_set/PHYBENCH_100/test.jsonl"
    output_path: "test_results/PHYBench/MAD/DeepSeek-r1-250528/results.jsonl"
    scheme: "mad"
    temperature: 0.0
    models:
      generator: "deepseek-r1-250528"
    mad_options:
      debate_model: "deepseek-r1-250528"
      max_rounds: 3
      config_file: "src/mad/config.json"
    tools: []

global_settings:
  concurrent_limit: 10
  aux_dir_base: ".aux"
