test_configs:
- name: gemini-2.5-pro
  input_path: problem_set/PHYSICS/test.jsonl
  output_path: test_results/PHYSICS/vanilla_review/Gemini-2.5-pro/results.jsonl
  scheme: vanilla_review
  temperature: 0.0
  models:
    reviewer: gemini-2.5-pro
  vanilla_review_options:
    max_error_times: 5
    target_times: 3
  tools: []
global_settings:
  concurrent_limit: 10
  aux_dir_base: .aux
