test_configs:
- name: gemini-2.5-pro
  input_path: problem_set/ABench/test.jsonl
  output_path: test_results/ABench/MAD/Gemini-2.5-pro/results.jsonl
  scheme: mad
  temperature: 0.0
  models:
    generator: gemini-2.5-pro
  mad_options:
    debate_model: gemini-2.5-pro
    max_rounds: 3
    config_file: src/mad/config.json
  tools: []
global_settings:
  concurrent_limit: 10
  aux_dir_base: .aux
